name: Sync repository to Community Organization

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Mirror push to ScribbleLabApp-Community
        run: |
          git config --global user.name "ScribbleCareBear CI"
          git config --global user.email "actions@github.com"

          git remote add mirror https://$GITHUB_ACTOR:${{ secrets.MIRROR_TOKEN }}@github.com/ScribbleLabApp-Community/ScribbleLabDocsKit.git
          git push mirror --mirror